### PR TITLE
Move Print button in sale/manage (Takings) to top right

### PR DESCRIPTION
**Pull request by daN4cat**
Fix to #145 issue.

### CODE REVIEW

**Comment by jekkos** [comment]
Ok I've pulled this change in to my local repo alright. 

Did you test the barcode generation on the receipts in the previous pr? Currently there's a problem appearing sales completion.

**Comment by jekkos** [comment]
Honestly I liked the more discrete print button a little more. But I get the point saying that it doesn't apply to printing selected rows, which would be a nice to have anyway. Currently users might think the print does a customized version of the takings layout, which in this case isn't really true (it just uses the default stylesheet for printing)

**Comment by daN4cat** [comment]
Sorry, I forgot to rebase and therefore I pushed things that were from your master by mistake.

I'll have a look into the receipt issue with barcode.

**Comment by daN4cat** [comment]
Crap... sale & receiving use the same barcode function but that cannot be EAN8 & 16.
We need to agree whether it's Code19 or Code128 as those ones are the only we can use for the receipts.

I need to add a new function for that.

**Comment by daN4cat** [comment]
Even item_kits need a fix.

**Comment by daN4cat** [comment]
Ok, but the item_kits issue is something else, at least it looks like that.

**Comment by daN4cat** [comment]
Pushed even a fix to #156 fix.

I hope you can now merge everything to master.

**Comment by jekkos** [comment]
There's another example in the sales model for searching the dates. You'll see that there are no more outer quotes (which is error prone anyway) because the escape function already does this step for us.

**Comment by daN4cat** [comment]
I used the last_query to print the query and it looked ok to me.
But I'll check again this evening and take into consideration your point, thanks for the feedback.
I simply reused that way copying what is used in customers and personnel for instance.
So if we have a better way I would need to make a change across other models to be consistent, but that in a separate step otherwise it gets too big.

**Comment by daN4cat** [comment]
Quickly check sale model and I see the following:

$this->db->where('sale_date BETWEEN '. $this->db->escape($inputs['start_date']). ' AND '. $this->db->escape($inputs['end_date']));

So you mean that item query should be:

'name LIKE %' . $this->db->escape_like_str($search) . '% OR ' .

I need to check better the % and what exactly the function escape_like_str does. As said it was a copy and paste from customer:

last_name LIKE '%".$this->db->escape_like_str($search)."%' or

I would need to fix that one too to remove the " as said earlier.

**Comment by jekkos** [comment]
I tihnk that it should be 

     last_name LIKE ".$this->db->escape('%'.$search.'%')." AND

**Comment by daN4cat** [comment]
Reading from here: http://www.codeigniter.com/user_guide/database/queries.html 

3. $this->db->escape_like_str() This method should be used when strings are to be used in LIKE conditions so that LIKE wildcards (‘%’, ‘_’) in the string are also properly escaped.

$search = '20% raise';
$sql = "SELECT id FROM table WHERE column LIKE '%" .
    $this->db->escape_like_str($search)."%'";

Based on the documentation what I've done seems correct, what do you think?

**Comment by daN4cat** [comment]
Pushed an extra fix to the language issue #156. By mistake I added a - to the Indian translation of "Last" in common_lang.php

**Comment by daN4cat** [comment]
Pushed fix to #155

**Comment by daN4cat** [comment]
Jekkos, can you please check and merge to master this batch?
I believe there is enough now to close this pr.

**Comment by daN4cat** [comment]
Fix to #152.

Jekkos, could you please check, merge and close this pr.

**Comment by daN4cat** [comment]
Jekkos, could you please check, merge and close this pr.

**Comment by jekkos** [comment]
Got it merged in now. I did have one last change that I had already on top of the latest github master and I rebased your changes on top of it, so hopefully this won't cause you too much trouble pulling this repo's changes back in?

**Comment by daN4cat** [comment]
I'm afraid this merge messed up things again....

**Comment by daN4cat** [comment]
Not sure I can see generate_receipt_barcode

**Pull request closed without merging**
