### PR TITLE
Do not show 'Send SMS' glyphicon, if phone number is not available.

### PR DESCRIPTION
**Pull request by RamkrishnaMondal**

### CODE REVIEW

**Comment by jekkos** [comment]
A lot of history for just al ittle change.. maybe squeash these commits into one?

**Comment by jekkos** [comment]
Or start a new branch from our current master and cherry pick that very last commit

**Comment by RamkrishnaMondal** [comment]
Lot of history due to fixation of a conflict and updating my fork,  changes only made on table_helper.php

**Comment by daN4cat** [comment]
Sorry I couldn't bother about doing a full merge cheery picking one file, so I simply copy and paste the two line of code, did a quick test and commit the change.

**Pull request closed without merging**
