### PR TITLE
Bootstrap and smarty

### PR DESCRIPTION
**Pull request by lcastillo0136**
i made a version whit bootstrap and Smarty php

### CODE REVIEW

**Comment by lcastillo0136** [comment]
Ready, thanks bro

**Comment by daN4cat** [comment]
Btw your version is 2.3.1 based, how different is that one from what we have in bootstrapUI branch?

**Comment by jekkos** [comment]
I appreciate the intention to make a contribution, but it would be easier to pick just those specific changes and make pull requests from a branch rebased on the repo's current master (or another dev branch). 

Most of the diffs here come from code that has evolved in newer versions. I'm not really eager to sort out what could be useful for the project and what not.

**Comment by daN4cat** [comment]
I agree, the intention is good indeed and welcomed but to extract what useful with the latest we have would be some work.

**Comment by lcastillo0136** [comment]
@daN4cat I did not know that already had a version with bootstrap and i dont know what are the differences between the versions of POS.

I dont want to merge whit the master proyect, i only want to share my version whit the world.

My version has bootstrap 3, full responsive, integration with Samrty-CI

you can test it in this [link](http://pos.onix-software.com)

thanks.

**Comment by lcastillo0136** [comment]
btw im new in Git, sorry if i make something wrong

**Comment by daN4cat** [comment]
no worries, it's fine.

The point is that bootstrapUI branch is the OSPOS vs with boostrap and it's build on top of a migration to Code Igniter upgrade to vs 3.0.4. So we progressed on that side and if you can contribute to boostrapUI that would be great.
We currently marked that version of OSPOS as vs 2.4.

**Comment by daN4cat** [comment]
I checked your version and it's a nice job indeed.

If you could check our bootstrapUI branch I'm sure you can contribute with some of your additions, there are nice touches here and there like icons and etc.
Your help would be great indeed to get the last push! :-)

**Comment by jekkos** [comment]
Nice looking version. Yes I'll add those nice looking icons in our version as well.

**Comment by jekkos** [comment]
Also the theme loading approach can be useful for incorporation in our latest version. Also tables in inventory and item stock look cleaner than the ones we have now. I might want to copy that code as well.

**Comment by lcastillo0136** [comment]
@jekkos Great!!

**Pull request closed without merging**
