### PR TITLE
More work around Suppliers/Brand

### PR DESCRIPTION
**Pull request by daN4cat**
- Added company_name to summary reports (name of the people didn't make sense in the reports)
- Added search by company_name (brand) in items
- Added company_name as column in items tabular view

### CODE REVIEW

**Comment by daN4cat** [comment]
I really don't know how to remove the history of commits and retain just the one I worked on.

Any clue?

**Comment by jekkos** [comment]
I think you'll need to checkout a new branch first, based on my current master. Then you'll have to move in your latest changes. So first you'll need to create a new branch based on my master

    git checkout  -b jekkos-master origin/master
    git rebase -i master

in this case origin is the name of the remote repository pointing to my github.

this last command will replay your changes on top of my current branch. In this case you will see a text file in which you can select the commits you want to add to my branch. If you want do remove some or maybe in this case squash a couple together, you can edit the file and save it. In this case just delete the lines that were already integrated by me. Also maybe rename the 'merge' commits as they're not really of interest in my repo.

If any conflict occurs during rebase then just resolve using git mergetool and then do a git rebase --continue
after it completes then history should be clean and you can push that jekkos-master branch to your github. I guess that'll be

     git push -u github jekkos-master

 Then from github you can make a pull request for jekkos-master to my repo.

**Comment by daN4cat** [comment]
I'm afraid I don't get anything different and neither a list of commits in the rebase file.
I simply get a noop. I'll try to search in the web for a solution, but tomorrow.

Worst case I'll create a new repo based on a new fork.

**Comment by jekkos** [comment]
Ok maybe verify that the contents of the jekkos-master branch is properly cloned from my repo? Maybe you have accidentally pulled in your own repo in the new branch?

**Comment by jekkos** [comment]
First command should have been like this (as far as I can follow your history)

     git checkout  -b jekkos-master jekkos/master

**Comment by daN4cat** [comment]
Thanks. I indeed used that command, I'll search around a bit more and figure out something.

**Pull request closed without merging**
