### PR TITLE
Spanish Translation completed

### PR DESCRIPTION
**Pull request by xepaez**
Spanish translation to all CSV files. Spanish translation updated - xepaez 20150424

### CODE REVIEW

**Comment by jekkos** [comment]
Looks good, will merge this later on (and regenerate language files)

**Comment by xepaez** [comment]
Good to know you'll merge it later, and good to know I can help. For future translations would you like me to generate the lang. files too?

**Comment by jekkos** [comment]
No that's not really necessary. It's good to see that you did the translation directly in the csv files and not in the generated ones. I'll generate then once I merge it.

**Comment by jekkos** [comment]
Ok merged in 69528b

**Pull request closed without merging**
