### PR TITLE
es Languaje Review and Update

### PR DESCRIPTION
**Pull request by sonnysk76**
Updates CSV for es Review

### CODE REVIEW

**Comment by daN4cat** [comment]
Thank you for the contribution.

I will look into this by end of the week, but there could be a bit more to do merging the bootstrap-tables work in master.

**Comment by jekkos** [comment]
Hopefully build will be green again in a minute.. hopefully it'll be more stable now. If so then we should take care of it more quickly

**Comment by daN4cat** [comment]
@sonnysk76 can you please take the latest master and make sure everything is translated as there has been some additions with new tables. Thanks

**Comment by sonnysk76** [comment]
Yes I'll do over the weekend.  Regards

**Comment by daN4cat** [comment]
Any update? There has been a couple of additions in the last few days.

**Comment by sonnysk76** [comment]
Working on it.

**Comment by zerote** [comment]
Hi guys, I just make some corrections on Spanish config file, just let me know if you want it and I´ll send it to you. 
BTW, great job here on this app!!

**Comment by sonnysk76** [comment]
Hello Zerote, you can send me the csv files and I can compare with the update I made

**Comment by zerote** [comment]
Please check attached file (Rename to config_lang.php removing txt extension)
Let me know if you need help on more English to Spanish translations, I´m pretty sure I can be useful




[config_lang.php.txt](https://github.com/jekkos/opensourcepos/files/298143/config_lang.php.txt)

**Comment by sonnysk76** [comment]
ES Review Completed

**Comment by daN4cat** [comment]
You need to upgrade the cvs files under translation dir, not the translated files.

**Comment by sonnysk76** [comment]
Yes the last commit is ok, csv modified and then I ran language_generator.php

**Comment by daN4cat** [comment]
@sonnysk76 I cannot merge your changes because there is a conflict.
It looks like you are using some older than master version of the translation and you are missing some more recent updates.
Please take the latest from master, reapply your translations or rebase your repo with latest master and recommit your changes.

**Comment by sonnysk76** [comment]
Ok, let me review.

**Comment by daN4cat** [comment]
Thanks

**Comment by sonnysk76** [comment]
Can verify?

**Comment by jekkos** [comment]
Seems that there are still conflicts? 

```This branch has conflicts that must be resolved```

**Comment by daN4cat** [comment]
I'll check this later, and see what the conflicts are about.

**Comment by daN4cat** [comment]
Merged the translations, but it's a partial story as I believe more translations should be sorted.

@sonnysk76 thank you for the work and maybe you want to take latest master and have a look into the rest of the files/translations when you have time.

**Pull request merged**
