### PR TITLE
Partial fix to #111 issues

### PR DESCRIPTION
**Pull request by daN4cat**
As discussed in #212 here the partial fix.

We can leave the full feature to a 2.3.4, this fix solves part of the problem anyway.

### CODE REVIEW

**Comment by jekkos** [comment]
I've done some research and I don't think that it's a good idea to start generating EAN13 codes ourselves. They should be unique and registered with a central authority first. 

Maybe we can solve the ean formatting problem with a sane validation on the involved format of the determined barcode input for the configured barcode type. If this validation fails, then just fallback to code128 which will always work.

**Comment by jekkos** [comment]
I've added the validation + fallback code in 83436d93ce3d8bf22a6c195979c1e2a1f2f053f6.

**Comment by jekkos** [comment]
Might be good to trigger the validation code in the item form as well (using jQuery).

**Comment by daN4cat** [comment]
Have you removed the EAN8 generation?

**Comment by daN4cat** [comment]
If that's the case, thank you very much!

You made the feature I surely needed completely useless and I need to scrap what you have done.

**Comment by jekkos** [comment]
Problem was that your scanner only accepts ean barcodes? My idea was that generating them might cause collisions with other existing barcodes out there as they're not registered in any official way.. 

If you like then I'll reintroduce it but only after enabling a config option to generate instead of using fallback.

**Comment by daN4cat** [comment]
That was the point I made already, having a config to generate only, not scrapping the code somebody spent time on it!!!

To be honest I found this approach quite disappointing :-(

The issue is not the scanner, the issue is that items come without any barcode and there are handheld printers that produce a small barcode to be attached to small items. EAN8 was there for that purpose because supported by those label printers.

I can agree that there might be collisions, I wan under the impression that padding the front with 0 was excluding the collision issue after having read in a forum that suggestion (it's ike a "192.168.x.x").

**Comment by daN4cat** [comment]
The use case was described in #111

**Comment by jekkos** [comment]
Yes I suppose that there will be some kind of range that's free to use, will look into that later today. So I'll add the following then

 * config switch for generating in the requested format if the item_number is empty. If this switch is not set then the barcode will be validated against the chosen format, and fallback mechanism will be activated if needed
 * extra jquery validation on the used barcode format for ean13 and ean8 to prevent input of invalid codes once a format is selected

**Comment by daN4cat** [comment]
I'm not sure I follow bullet point 2, the issue here is to generate barcodes if the field is empty. And the first option is just for that. If empty generate it with EAN{8, 13}. If no option the seed is always used.

We can print all the barcodes in code{39. 128} and that will do. There is no requirement to print the barcode in EAN{8, 13}, only if an external printer supports that can print in EAN{8, 13}. The scanner will detect the two barcodes no matter the "graphical format" and match the UPC code.

That's what I wanted to do, splitting generation out of printing.

Of course we could always leverage a recognition of the barcode and be smart in producing the correct barcode printout (in case somebody has a EAN only scanner, but I don't think there is such case).

So what is that jquery needs to validate?

**Comment by jekkos** [comment]
I added this validation bit in the item number check code. So once a user enters a new item and has ean8 selected as format, he should enter a ean8 formatted barcode in the item_number or else leave it empty. This will still allow the generation to work (only if the item_number is empty) and prevent the user from entering invalid barcodes

**Comment by jekkos** [comment]
Ok so in this maybe the first part will do. If I add the generation only for ean then we'll be fine. Ill post a patch for that hope you can take a look and see if it's ok for you.

**Pull request closed without merging**
