### PR TITLE
Translate field date_or_time_format to Spanish

### PR DESCRIPTION
**Pull request by jlctmaster**
Add translate to field date_or_time_format on config location tab.

### CODE REVIEW

**Comment by daN4cat** [comment]
not sure this is the way to proceed, @jekkos please check this

**Comment by daN4cat** [comment]
I merged these two changes in master

**Comment by jekkos** [comment]
We should add these changes to weblate branch as well.. will pull them in so the strings can be translated.

**Comment by jlctmaster** [comment]
Hello @daN4cat, I have already seen the translation changes in the master branch, do this PR because I saw that the project has a branch for the translation management (weblate), then I ask, I close this PR and someone else does the translations correct?

**Pull request merged**
