### PR TITLE
Fixes to phppos to ospos 2.3.4 migration script #258

### PR DESCRIPTION
**Pull request by daN4cat**
Fixes to phppos to ospos 2.3.4 migration script #258

### CODE REVIEW

**Comment by jekkos** [comment]
Ok great thanks for testing, one thing is that the patch should be applied on the original migrate script (dist is the concated result of tables, migrate and constraints). Will try to see if I can solve that quickly.

**Comment by daN4cat** [comment]
Let me fix that, I also forgot to make the change for admin entry.

**Comment by daN4cat** [comment]
OK, fixed.

**Comment by jekkos** [comment]
Ok great, thanks for finalizing this.

**Pull request merged**
