### PR TITLE
Include mod_rewrite to redirect to ./public/ #1491

### PR DESCRIPTION
**Pull request by objecttothis**

### CODE REVIEW

**Comment by jekkos** [comment]
Ok something is wrong with the travis setup for different branches..  can't seem to merge due to the failing check

**Comment by objecttothis** [comment]
That's probably my fault. I'm new to github

_Sent from my Android XT1575 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by objecttothis** [comment]
@jekkos, I may have read your comment wrong.  My first name is Travis, so it confused me.  None the less, there may be something wrong with my setup as well.

**Comment by daN4cat** [comment]
It's TravisCI, a cloud based Continuous Integration used by @jekkos to "test" and build the OSPOS  deployment package. It's triggered every time something is submitted to Github. 
I'm just explaining you how stuff works here :-)

**Comment by daN4cat** [comment]
I submitted the change making it available to any Apache version.

**Pull request closed without merging**
