### PR TITLE
Add office menu.

### PR DESCRIPTION
**Pull request by SteveIreland**
This will add an "office modules" perspective to the menu.  I know that this isn't something that will be included in 3.1 so it's not "finished' in the sense that I didn't update the database.sql or tables.sql.  But I'm throwing it out for review and testing (if anyone has time to test it).

Since I had to change the config_general configuration tab I encountered some small issues with the captcha config which I cleaned up a bit.

### CODE REVIEW

**Comment by daN4cat** [comment]
@SteveIreland you need to fix the translations to be in en-US

**Comment by SteveIreland** [comment]
I just removed the original pull request and starting to test the rebased and fleshed out version and expect to resubmit it tomorrow.

**Comment by SteveIreland** [comment]
It seems when I deleted the pull request the system closed this ticket.  @daN4cat  please reopen.   Sorry.

**Comment by odiea** [comment]
@SteveIreland It says your office-menu branch has been deleted so it will not reopen it.

**Comment by SteveIreland** [comment]
Thanks.  I forgot that I never created an official "issue" for this.  I'll open up a "New Feature" issue so that there can bee some feedback that persists beyond the life of the next pull request.

**Pull request closed without merging**
