### PR TITLE
Spanish language review

### PR DESCRIPTION
**Pull request by sonnysk76**
Review completed for 3.0

### CODE REVIEW

**Comment by jekkos** [comment]
Integrated in latest master. Thanks for the pr!

**Comment by daN4cat** [comment]
@sonnysk76 can you please check the config_lang.php last line and translate Theme in Spanish. You can also just copy the translation here and I can add it to the file.

**Comment by sonnysk76** [comment]
I cant access from my pc. But I found    Theme   > Tema

**Comment by daN4cat** [comment]
Thanks, I've updated the translation

**Pull request closed without merging**
