### PR TITLE
Patch 4

### PR DESCRIPTION
**Pull request by flodef**
Add files to fr (French) folder and translate some of them.
The others can stay as this until I or someone translate them.

### CODE REVIEW

**Comment by jekkos** [comment]
OK thanks for the pull request, will look into this as soon as I find the time.

**Comment by flodef** [comment]
Thanks to you and Happy New Year :-)

**Comment by jekkos** [comment]
Ok I think these files are the system language files themselves. Those can be found around the internet as well. For example here https://github.com/ferniwob/Codeigniter-2.2-french-languaje-/tree/master/french

Do you think this is a complete enough translation to add them like that?

**Comment by flodef** [comment]
Damn, I didn't know that. I translated the files for nothing ... Oooops.
I checked the link and the files are better on it.
So, I'll upload those instead and make another pull request.

**Comment by flodef** [comment]
The files are updated and good to be added :+1:

**Comment by jekkos** [comment]
ok so I suppose translations are complete now? Will merge them in then.

**Pull request merged**
