### PR TITLE
Fix/excel template downloads

### PR DESCRIPTION
**Pull request by williamchanrico**
Pointed "Download Import Excel Template (CSV)" download path to the correct import_customers.csv & import_items.csv location.

### CODE REVIEW

**Comment by williamchanrico** [comment]
Behaviour before fix:
GIF

**Comment by odiea** [comment]
Thanks for finding this issue. With your commit it is back to working now.

**Comment by daN4cat** [comment]
Yep, there is always that odd thing you forgot to test and in the end was not right....
We'll pull the PR later.

**Comment by daN4cat** [comment]
Thanks for the help

**Comment by williamchanrico** [comment]
Yeah, I'm glad I could help.

**Comment by daN4cat** [comment]
Merged and in master.

Thank you again for the contribution.

**Comment by betocaceresa** [comment]
Muchas gracias @williamchanrico  ya no tengo ese problema!!!

**Pull request merged**
