### PR TITLE
Add date range to Items view #132

### PR DESCRIPTION
**Pull request by daN4cat**
Use inventory date to narrow touched items based on selected date range #132

### CODE REVIEW

**Comment by odiea** [comment]
on Initial date search items appear ok. The item search feature pulls up a suggestion but no item. When I added a new item with the date picker set to todays date the new item does not show until I go back into items. It is not being picked up with the date picker at all.

**Comment by daN4cat** [comment]
OK, I'll have a look into that. Probably I touched something by mistake at the last minute because it was fine (the search and pull the item).
And I'll look into the other issues as well.

**Comment by jekkos** [comment]
Thanks for that, nice feature btw.

**Comment by daN4cat** [comment]
By mistake something went in in model item that was not supposed to be in.

I tried the search, I can see suggestion and the item is fetched.

Bear in mind that search takes always priority, so there is no search of item in narrowed time range to avoid conflicts that might complicate matter.

Otherwise I need to add a checkbox before the time range to make it effective or not.

All the other checkboxes apply to the selected time range.

I'm travelling abroad, so not sure I can look into this more next couple of day, therefore apologies in advance for the quick fix & test and maybe another failure.

**Comment by jekkos** [comment]
I'll look into it when I have the time. The idea of disabling date filtering on search is good, I'd like to introduce that to takings as well.

**Comment by daN4cat** [comment]
I found the time to check why the selected range was missing the end date items and fixed.

**Comment by odiea** [comment]
The update worked well for the items to show now. But I am still getting this issue . The first pic is the intial item inout. The second is the edit item pic. Notice the tax rate.
2015-09-23 14_29_18-once again thrift -- powered by os point of sale
2015-09-23 14_30_06-once again thrift -- powered by os point of sale

**Comment by odiea** [comment]
I just noticed in reports date range, it looks like you forgot to include the language file for some  items

**Comment by daN4cat** [comment]
Could you please create a new issue for the Tax bug? It would help to write down the exact sequence to reproduce that. That for sure has nothing to do with my changes related to date range in Items.
I will look into that under a separate bug.

With regards to Date Range and language translations, it's all submitted as far as I can see: https://github.com/jekkos/opensourcepos/blob/master/translations/reports_lang.csv and search for instance for "reports_this_month_last_year". It's there.

**Comment by daN4cat** [comment]
jekkos, it looks like the feature is fine since I reverted the extra file submission and fixed the data range boundary issue.

After your review maybe you can integrate unless you want to have some other issue/suggestion?

**Comment by jekkos** [comment]
I'll integrate it later today. Thanks for the work.

**Comment by daN4cat** [comment]
:+1:

**Pull request merged**
