### PR TITLE
add feature to override view as new theme

### PR DESCRIPTION
**Pull request by yllumi**
This is simple implementation for theming. I want to change template style without changing any files in core system. So I override CI_Loader to embed custom template view path so system will use custom view if it exists.

The custom template is placed in ./templates/theme_folder/ and you can manage which theme is used in ./application/config/theme.php. I have create one simple theme based on bootstrap which is used flatly style from bootswatch.

### CODE REVIEW

**Comment by jekkos** [comment]
Nice idea. Finally somebody that brings up some ui improvements. I'll check it out later today.

**Comment by yllumi** [comment]
Perhaps you can merge it. I have a plan to implement any bootstrap admin template like [AdminLTE](https://almsaeedstudio.com/themes/AdminLTE/index2.html) that makes the appearance responsive and more beautiful.

**Comment by kdkrun** [comment]
This is very nice...

**Comment by odiea** [comment]
Nice idea. Is there a way to change it from within the ui?

**Comment by yllumi** [comment]
@odiea if you want to change the style or layout, you can override any of view file you want, you can add or remove any element to it. Just copy the default view file that you want to change to templates/template_folder/views/ and system will use that view.

**Comment by odiea** [comment]
Thanks.

**Comment by jekkos** [comment]
All in all nice contrib. But there's still some issues remaining

* clean style, looks good.
* feedback bar partly occludes the menu on top of the screen
* font sizes aren't really consistent, eg maybe we should decrease font size for the detail views as most of them need vertical scrolling now
* add an option to change themes in the config (so users can revert to original if they want)

**Comment by yllumi** [comment]
Ok, I got it. I have made some improvement after this pull request. Maybe I will fix some of other point you mentioned first then I will send a new pull request.

**Comment by jekkos** [comment]
Thanks for that. I think we'll want to integrate this in scope of 2.4 release (as 2.3.3 was already feature complete, just bugfixes). Good to have a bit of UI redesign for a new major version.

**Comment by cpl2015** [comment]
Wow! really nice interface. I am facing a problem, it is always printing the 'TOPBAR' contents (ie current date & time, employee name and logout! link) on top of the printed receipt / invoice. How to prevent that ?

**Comment by jekkos** [comment]
Think someone will need to adapt the print css stylesheet to fix that issue. Also looks like most of the UI is now responsive as well (items, sales tables).. except for the sale and receiving register.

Didn't check reports yet but all in all this is an improvement we've been waiting for.

**Comment by cpl2015** [comment]
Playing  with OSPOS and Bootstrap !

**Comment by onyema3** [comment]
Nice!

**Comment by kdkrun** [comment]
Wow its very nice.. can you please give some guidance to do same with our system... Please

**Comment by cpl2015** [comment]
The bootstrap theme is created by 'yllumi', I have only added some pictures, changed some icons and edited some files.

**Comment by cpl2015** [comment]
Some more fun !


Theme: "SPACELAB"



Theme: "DARKY"

**Comment by kdkrun** [comment]
Would you like to share your theme file with us... ?

**Comment by cpl2015** [comment]
Of course ! I have downloaded the theme files from here : https://bootswatch.com/
But you have to change each and every button codes in all the register view files.

**Comment by cpl2015** [comment]
@yllumi 

I can see, you have added some code to toggle menu icons on mouse hover, but  is not working with FLATLY, but working fine with SPACELAB theme. Also tested with some other themes, not working.
It will be great if you can add some dynamic mouse hover effect to the menu  buttons  at the body also.
Thank You.

**Comment by odiea** [comment]
Here's the code for using company name on your partial header.
 	<span class="navbar-brand" id="company_title"style="font-size:14pt"><?php echo $this->config->item('company'); ?></span><br />

**Comment by daN4cat** [comment]
Hi @cpl2015, since everybody here helps out contributing in a part they are more familiar with, it would be nice to have let say the SPACELAB theme proposed as new OSPOS UI look'n'feel.
Do you think you could contribute it? Or maybe have it submitted to your Git for other people to benefit from?

**Comment by jekkos** [comment]
Maybe these multiple themes are a maintenance nightmare indeed. We might just omit the original to easy the amount of work a little bit.

**Comment by daN4cat** [comment]
Yes, we need to break away from the old UI and at least "bootstrap" the core and then templating the bits.

We make the core UI one default bootstrap template and people can upgrade to other templates "subclassing".

**Comment by jekkos** [comment]
Once bootstrapped I think there will indeed be more fexibiliy for theming. At least we shouldn't be maintaining duplicated source. Changing stylesheets only should be sufficient to switch a theme.

**Comment by daN4cat** [comment]
Agreed

**Comment by daN4cat** [comment]
I will work on that in my branch trying to move everything to the base code and remove old stylesheets. Let see if I can make it configurable from config too.

**Comment by odiea** [comment]
@daN4cat  Have you had a chance to play with the css to create buttons for sales and receivings?

**Comment by daN4cat** [comment]
My branch boostrapUI has that and  coming from cpl2015 tweaks

**Comment by odiea** [comment]
Thanks I will download it and steal some code from you.

**Comment by daN4cat** [comment]
Please bear in mind that I need to move the bootstrap-isation to the core code and leave just the bits to templates. So things will reshuffle a bit.

**Comment by jekkos** [comment]
What do you mean exactly with core code? I suppose bootstrap will only have impact on the views and eventually some helper functions that buildup the tables?

**Comment by daN4cat** [comment]
Base code, I meant core of ospos not ci

**Comment by odiea** [comment]
The thing that baffles me is why does Logout and Takings display that text blue color. I set mine up to use Spacelab as the display without using the template folder.

**Comment by daN4cat** [comment]
I need to fix some of that stuff, I just merged the code it's not final.

**Comment by odiea** [comment]
This is on the style sheet.
Replacing the original feedbackbar setting from original css 
Or jut changing the current to bottom will place the feed back bar to the bottom.
#feedback_bar
{
	position:fixed;
	bottom:0;
	left:0;
	width:100%;
	height:55px;	
	position:fixed;
	opacity: 0;
	filter: alpha(opacity=0);
	z-index:1;
	line-height:3.3;
}


#footer
{
	position:relative;
	margin-top:25px;
	margin-bottom:15px;	
	text-align:center;
	font-size:11px;
	color:#777777;
	clear:both;
	
}

This will bring the page to proper alignment.
* {
   font-size: 12px;
   line-height: 1.5;
}

replacing this in register will give you a white button background.
#sales_overview > a
{
	color:#ffffff;
	top:3px;
	right:99px;
	text-decoration: none;
}

Replacing this in partial header will give you the company name.
		/*<span class="navbar-brand" id="company_title" style="font-size:14pt"><?php echo $this->config->item('company'); ?></span>*/

Commenting this out in bootstrap.css will align the form ok but still does not show form boxes.
.glyphicon-menu-up:before {
  content: "\e260";
}

/** {
  -webkit-box-sizing: border-box;
  -moz-box-sizing: border-box;
  box-sizing: border-box;
}
*:before,
*:after {
  -webkit-box-sizing: border-box;
  /*-moz-box-sizing: border-box;
  box-sizing: border-box;
}*/
Hope this helps someone.

**Comment by daN4cat** [comment]
Looks great, thanks! Once I finished with this database migration script test I will go back and look into bootstrap stuff again.

**Comment by odiea** [comment]
Other than the form boxes not showing I think the other issue I cant figure out is trying to get the totals to show under the Total line and not 3 or 4 lines below it.
2016-02-02 16_50_46-ugly sweater store -- powered by os point of sale

**Comment by odiea** [comment]
So here is the css I used in style.css. I just changed the name for each form .
 The only form I could not change was New Item. I guess I cant find whats calling that one. You will also have to change some of the form info so that common_fields_required_message shows properly. You may not like some of the colors.
#employee_form 
 {
  display: block;
  width: 97%;
  height: 24px;
  padding: 8px 12px;
  font-size: 14px;
  line-height: 1.42857143;
  color: #0099ff;
  background-color: #ffffff;
  background-image: none;
  border: 2px solid #0099ff;
  border-radius: 4px;
  border-color: #0099ff;
}

**Comment by odiea** [comment]
Here is my current css for Spacelab. Hopefully you can use it as a base to work from.
[style.txt](https://github.com/jekkos/opensourcepos/files/116701/style.txt)

**Comment by odiea** [comment]
So far it appears we should integrate space lab as the default ospos appearance and then add the templates. The biggest issue I see is changing the buttons in register and receivings also in Items details some tweaking needs to be done for the view to show properly..

**Comment by daN4cat** [comment]
Indeed, we'll look into that.

**Comment by daN4cat** [comment]
The issue of the totals overlapping the footer is simple, just edit the footer.php in the templates/view (under partial) and make sure there are just two </div> as first lines before the <div id="footer">.

I've edited the files and removed. I'll commit the fix to my branch later.

**Comment by odiea** [comment]
Yes I got that figured out. What I wanted was the numbers to show directly below the total line.

**Comment by daN4cat** [comment]
OK. BTW touching the original style.css is not a good idea.
Those need to go to another css overriting the default

**Comment by odiea** [comment]
Ok. I guess I need to create a different css for each template other than adding to  the style sheet. It appeared to me he just created the style sheet as an addon because it's not included with the different templates.

**Comment by daN4cat** [comment]
I need to check

**Comment by odiea** [comment]
Your about 8 hrs ahead of us so who won the super bowl? HA HA

**Comment by daN4cat** [comment]
No idea, but I can tell you that Ireland and Wales draw the match in the Rugby 6 nations today.

**Comment by daN4cat** [comment]
yes you are right, style.css doesn't come with the template. Just bootstrap is.
So you are correct with your changes

**Comment by odiea** [comment]
Well I guess the Irish in me hopes the Irish win.

**Comment by daN4cat** [comment]
You won the last two Rugby 6 nations in a row. No team ever won 3 in a row.

**Comment by odiea** [comment]
Thanks.

**Comment by daN4cat** [comment]
In your style.css Instead of:

> * {
>    font-size: 12px;
>    line-height: 1.5;
> }

use

> .container {
>    font-size: 12px;
>    line-height: 1.5;
> }

So you don't affect the font size of the footer.

**Comment by daN4cat** [comment]
You don't need to create a footer in css, just put in footer the following:

> 	<div id="footer">
> 		<div class="jumbotron">
> 			<?php echo $this->lang->line('common_you_are_using_ospos'); ?>
> 			<?php echo $this->config->item('application_version'); ?>.
> 			<?php echo $this->lang->line('common_please_visit_my'); ?>
> 			<a href="https://github.com/jekkos/opensourcepos" target="_blank"><?php echo $this->lang->line('common_website'); ?></a>
> 			<?php echo $this->lang->line('common_learn_about_project'); ?>
> 		</div>
> 	</div>

and you get the correct footer using bootstrap container

**Comment by odiea** [comment]
Thanks for the tips. I think I placed the footer css there when I was trying to figure out why the feedback bar wasn't working correctly so I just left it there.

**Comment by daN4cat** [comment]
And it doesn't make sense to retouch the buttons because the buttons class need to change in the code to make full use of bootstrap. So the change need to go in the code first.

**Comment by odiea** [comment]
Yes. That's what I was thinking too.

**Comment by daN4cat** [comment]
I'm changing the code at the moment....

**Comment by daN4cat** [comment]
OK, I pushed a batch of new changes in my bootstra UI branch.

I used some of your style.css changes, applied to flatly only.

Next step I need to make flatly being the default bootstrap theme with another one in templates as example for people that want to change the base one.

**Comment by odiea** [comment]
When you get a chance try out mine. I think it's a little farther ahead.
http://ospos.25u.com:8080/noicons/index.php/home

**Comment by daN4cat** [comment]
I close this PR because it's now obsolete.

All the temporary branch daN4cat/bootstrapUI submissions are against the original topic in #116 .

Please follow up the discussion there.

**Pull request closed without merging**
