### PR TITLE
Date or Time Format

### PR DESCRIPTION
**Pull request by jlctmaster**
Add Support for filter reports with date or time format from last commit into master branch

### CODE REVIEW

**Comment by eremiter** [comment]
Environment: Windows + php5.5 + apache 2.4 + mysql5.5
Click store configuration(OR reveivings OR Sales) operation gets stuck, other menu runs slowly

**Comment by daN4cat** [comment]
@jlctmaster I merged this into master, however I don't think it's working as expected. I committed to master just to keep merging these changes and avoid rebase issues going forward but you need to take latest master test and fix.
If you don't select date & time in Store config nothing is broken (that I could spot), but if you select it, date & date jquery plug in works fine but SQL query don't work.

**Comment by odiea** [comment]
Takings tables quit working for me.

**Comment by daN4cat** [comment]
Post issue in #932

**Pull request merged**
