### PR TITLE
Improve spanish translation

### PR DESCRIPTION
**Pull request by rotrico**
master branch missed some translations to spanish, some strings showed in blank when opensourcepos language is set to spanish.
I added them, now spanish language shows ok.

### CODE REVIEW

**Comment by jlctmaster** [comment]
Hello, I added the missing translations some time ago directly by the [Weblate](http://weblate.jpeelaer.net/) project, although they have not yet mixed it with the master branch, I do not know the procedure for that. If you check this [link](http://weblate.jpeelaer.net/languages/es/), you will see that the Spanish language is 100% translated.

There is need to mix it with the project.

**Comment by rotrico** [comment]
Hello Jorge,

Sorry, I'm a little confused: is Weblate the "official" procedure to follow in order to translate opensourcepos?
I supposed that the procedure was to edit directly .php files, as the other project files.

Looking at github, I see your last commit (17 of april), but on 22 of april joshua1234511 made another commit, is it possible that he introduced some changes that were not covered by your translation? Also your last edit in Weblate is from 21 of april, one day before joshua1234511 commit.

I checked your changes in 21 of april, them reffer to different strings I translated today, maybe the "100%" number in weblate reffers to an old version of opensourcepos? (I don't know if weblate has a direct link with github to autorefresh with changes in code, or if i'ts a manual procedure done by developers).

Also you can check my changes to verify If both translated the same, or if I translated new strings (I think that we translated different strings, but I'm not sure if I checked correctly your weblate repository).

Thanks.

**Comment by daN4cat** [comment]
@jekkos it looks like Weblate needs a resync with the code in master. Maybe we can accept this PR and then resync all.

**Comment by jekkos** [comment]
OK resync done.

**Pull request merged**
