### PR TITLE
Pequenas modificações

### PR DESCRIPTION
**Pull request by arteiro**
Alterados e incluídos palavras nos arquivos .csv

### CODE REVIEW

**Comment by jekkos** [comment]
Thanks for the translations. However we currently don't support any translation on the readme (or we'll have to switch to another language) so if you could then maybe omit that part?

**Comment by arteiro** [comment]
Ok, I do not know how to use the right desktop github, put on my copy to anyone who is Brazilian not hit much. if you give problem retreat there.
So I made one with .csv.
Hugs
Thank you

**Comment by daN4cat** [comment]
Merged

**Comment by arteiro** [comment]
OK,

Thanks

**Pull request closed without merging**
