### PR TITLE
fixes for giftcard

### PR DESCRIPTION
**Pull request by joshua1234511**
While I was checking the working, I noticed that gift card can add customer, but for sale it is never checked so I added code check for customer if gift card is assigned. 

Attached scrrencast: https://www.screencast.com/t/nMfwmylKFYO

The code I added checks if gift card has customer assigned to it, if it does that the customer should match, else gift card will give error invalid Customer.

### CODE REVIEW

**Comment by daN4cat** [comment]
Hi, the reason why giftcard are anonymous is because you may give as a gift to somebody and not be named.
It was discussed in the past and so I would not enforce any rules at sales time between customer and giftcard.
As long as the code is fine it should be OK. Unless you have some other scenario in mind where it could be wrong?

**Comment by joshua1234511** [comment]
Usually  when we give birthday cards to customers, or anniversary we provide gift cards fro them. this bonus is only for them. and not transferable. 
The other cards can still be there. 
This is also helpful in case of misplacing of cards

**Comment by joshua1234511** [comment]
Doing the above you can have both 
1: gift to somebody and not be named.
2: gift to somebody and restrict.

**Comment by daN4cat** [comment]
I want to hear an opinion from other people too.

**Comment by joshua1234511** [comment]
Yes that is there
It must be agreeable to all. 
This was just my opinion,

**Comment by daN4cat** [comment]
@jekkos @odiea @SteveIreland any view?

**Comment by odiea** [comment]
I will download his branch and see how it does.

**Comment by odiea** [comment]
The only issue I see is when you start with generate in series they auto number correctly but when you switch over to a Random number say 1234-56 and then go back to series the series then uses the 1234 and not the previous number of say 45. Other then that it appears to be working. Eventually I hope he will add the ability to add a customer to the gift card form instead of add new customer then add new giftcard. Giftcards on the fly

**Comment by daN4cat** [comment]
You mean when creating a new giftcard for a customer not in the system? That would be handy but it's probably difficult to manage as it implies two modals

**Comment by odiea** [comment]
Yes but we can dream can't we.

**Comment by daN4cat** [comment]
Indeed

**Comment by daN4cat** [comment]
So @odiea you are fine with this change. @jekkos any opinion?

**Comment by odiea** [comment]
It is another nice option. So yes.

**Comment by daN4cat** [comment]
Ok if no more feedback I'll merge this next days.

**Comment by jekkos** [comment]
I agree to merge as long as one can still make giftcards without having to add a customer.

**Comment by odiea** [comment]
Yes you can still use blank customer giftcards. If the customer name is selected he can also use a blank name giftcard.

**Comment by daN4cat** [comment]
Merged and submitted to master.

**Comment by daN4cat** [comment]
I was wondering, in the sale register it would be nice to suggest the gifcard number as it is entered, like the search suggestion we give for customer or items.
In case a customer is selected the suggestion should be narrowed down to the giftcard allocated to the customer.

@joshua1234511 is that something you can look into as a nice user experience addition?

**Comment by joshua1234511** [comment]
https://github.com/jekkos/opensourcepos/pull/1273

**Pull request closed without merging**
