### PR TITLE
SMS message sending feature #472

### PR DESCRIPTION
**Pull request by daN4cat**

### CODE REVIEW

**Comment by jekkos** [comment]
@daN4cat @RamkrishnaMondal Thanks for this contribution. It might be nice to support implementation of a spi through a comon api for sending sms. A good usecase here would be to attach a cell phone to pc over serial line and send messages using a simcard inside this cell phone. This might be a lot cheaper in comparison with using a sms gateway as most providers give a lot of free sms on prepaid cards.

**Comment by daN4cat** [comment]
The API in library/sms.php should be generic enough. However if you want to dynamically load custom interfaces for extra functionality even at configuration time the design is not there indeed.

**Comment by RamkrishnaMondal** [comment]
@jekkos  I was also thinking of using an 'AT command supported GSM' modem alongwith 'kannel', as I am on Ubuntu based Linux.

Here is a nice how to : https://aacable.wordpress.com/2012/11/26/howto-configure-your-local-http-gateway-using-kannel-on-ubuntu/

**Comment by RamkrishnaMondal** [comment]
@daN4cat  I just read the 'read me' of ospos, was expecting my name there. Perhaps you have forgotten to update that file. Not a big issue though.

**Comment by daN4cat** [comment]
Hi @RamkrishnaMondal you are right, apologies for that. I checked many things but forgot to update the COPYING file. Let me do that now.

**Comment by RamkrishnaMondal** [comment]
Thanks.

**Comment by daN4cat** [comment]
done

**Pull request merged**
