### PR TITLE
New Version

### PR DESCRIPTION
**Pull request by nano-riff**

### CODE REVIEW

**Comment by jekkos** [comment]
Yes this pull request is kind of messy.. I'll try and cherry pick that latest commit to see what happens

**Comment by jekkos** [comment]
Ok can't make sense of this, I have no idea where you started from with that latest commit. Might be better to sync with my repository first and reapply your changes on top of that.

**Comment by daN4cat** [comment]
I believe @nano-riff intention was to rebase their repo, probably the PR went the opposite way?

**Comment by nano-riff** [comment]
Sorry for this. As I am not used to this and using it is not very intuitive... 
I will probably make a new fork and then work on this, ok?

**Comment by daN4cat** [comment]
You can do a fork, or simply repeat the same pull request but selecting the repo the other way round

**Comment by nano-riff** [comment]
My question is: do I start the PR from jekkos repository or from mine...
I probably did it from mine, but can't remember exactly

**Comment by daN4cat** [comment]
Do the opposite of the default. It will default in pushing to jekkos

**Comment by daN4cat** [comment]
When inverting the master in the drop down you might get the drop down not to show what you wanted, click on "compare across forks" link to get the drop down boxes in full and select the correct repositories.

**Comment by daN4cat** [comment]
I just did one test using my repo and here what you should see:

image

**Comment by daN4cat** [comment]
Of course replace my name with yours.

**Comment by nano-riff** [comment]
OK, I'am getting this:
opensource
and now I click on "Create pull request" isn't it?

**Comment by daN4cat** [comment]
OK, it cannot merge automatically. 
If you have no particular reason to do that it's probably better if you save any translation file you have done with the old and take all the latest code from jekkos/master and use it as new starting point for the translation, copying and pasting your translated files.

I believe it's easier to do like that.

**Pull request closed without merging**
