### PR TITLE
Adding Azerbaijani language for 3.2.0

### PR DESCRIPTION
**Pull request by objecttothis**

### CODE REVIEW

**Comment by jekkos** [comment]
Ok thanks for the patch, this is indeed the last thing needed to make it work.
I suppose translations is still a work to be done?
In that case I'll wait the merge until 3.1.1 is ready.

**Comment by daN4cat** [comment]
It's better to have the translations together with the change of language.
If this comes by end of the weekend I can merge it in 3.1.1. If not we skip to 3.2.0

**Comment by objecttothis** [comment]
that's why I marked it as being for 3.2.0. it won't be translated by the weekend and I didn't want to hold up 3.1.1

**Comment by daN4cat** [comment]
ok, clear

**Pull request merged**
