### PR TITLE
Update common_lang.php

### PR DESCRIPTION
**Pull request by pablos1rvent**
I change "Date" in english, in spanish is "Fecha".
I also change a UTF-8 character

### CODE REVIEW

**Comment by daN4cat** [comment]
What about reviewing all the Spanish translations? They haven't been updated for a year at least so it's better to get a complete update of what is currently in 3.0.

**Comment by pablos1rvent** [comment]
@daN4cat Yeah! I think I can update a little bit ^^

**Comment by daN4cat** [comment]
That would be great. Thanks.
Once done happy to integrate the translations.

**Comment by pablos1rvent** [comment]
@daN4cat Don't worry :3, I'm new barely in GitHub, sorry if I break something or crash any database hahaha

Greetings :D

**Comment by daN4cat** [comment]
BTW, please edit the files in translations folder, all the csv.

Once done, run the generate_language.php from the root.

**Comment by daN4cat** [comment]
@pablos1rvent do you have any news with regards to the Spanish translations?

**Comment by sonnysk76** [comment]
Hello @pablos1rvent @daN4cat  I can also help with the spanish translation, I just discover this project and working in an installation for a coffee shop.

**Comment by daN4cat** [comment]
That sounds great, see my comment above about what to change a generate translations

**Comment by pablos1rvent** [comment]
@sonnysk76 @daN4cat Hola xD
Well, recently I'm in a new project with this great tool (OSPOS) and I don't have time to translate, well the spanish in this tool is good but have some mistakes, I think is on 70% and can be easy to translate ^^

Saludos! (Greetings in Spanish)

**Comment by pablos1rvent** [comment]
@daN4cat One more thing, with the edit sale (hahaha sorry, I don't found nothing at this time), I have found the other answer of @RamkrishnaMondal that I can edit the sale with the receiving mode, but that creates a new one, I need to edit the existing sale, and you tell me that is implemented, but I don't see nothing. 

If you help me on that I can translate the spanish to 100% haha

**Comment by daN4cat** [comment]
The Spanish translation is for you guys, I'm fine with the English version.

Given that this merge is partial I close it and way for the next one to come.

**Pull request closed without merging**
